version: "2"
services:
 catalogo:
  build: .
  ports:
   - "3000:3000"
  links:
   - redis:redis
 redis:
  image: "redis:alpine"
  command: redis-server --requirepass suasenha --appendonly yes
  ports:
   - "6379:6379"
