version: "2"
services:
 catalog_api:
  build:
   context: ./catalog_api
   args:
    PORT: 3000
    MONGODB_USER: root
    MONGODB_PASSWORD: suasenha
    MONGODB_HOST: mongo_catalog
    MONGODB_PORT: 27017
    MONGODB_DBNAME: catalog
    INSERT_PRODUCTS: 1
    REDIS_PORT: 6379
    REDIS_HOST: redis_catalog
    REDIS_PASSWORD: suasenha
  ports:
   - "3000:3000"
  depends_on:
   - "redis_catalog"
   - "mongo_catalog"
  links:
   - redis_catalog:redis_catalog
   - mongo_catalog:mongo_catalog
  networks:
   - catalog
 mongo_catalog:
  image: mongo:3.4.2
  environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=suasenha
  ports:
   - "27017:27017"
  command: mongod
  networks:
   - catalog
 redis_catalog:
  image: "redis:alpine"
  command: redis-server --requirepass suasenha
  ports:
   - "6379:6379"
  networks:
   - catalog
networks:
 catalog: