version: "2"
services:
 frontend:
  build:
   context: ./frontend
   args:
    PORT: 8080
  ports:
   - "8080:8080"
  depends_on:
   - "recommendation_api"
  links:
   - recommendation_api:recommendation_api
  networks:
   - shared
 recommendation_api:
  build:
   context: ./recommendation_api
   args:
    PORT: 3001
    REDIS_PORT: 6380
    REDIS_HOST: redis_recommendation
    REDIS_PASSWORD: suasenha
    CATALOG_API_URL: http://catalog_api:3000
    RANKING_API_URL: https://wishlist.neemu.com/onsite/impulse-core/ranking/
  ports:
   - "3001:3001"
  depends_on:
   - "redis_recommendation"
   - "catalog_api"
  links:
   - redis_recommendation:redis_recommendation
   - catalog_api:catalog_api
  networks:
   - shared
 catalog_api:
  build:
   context: ./catalog_api
   args:
    PORT: 3000
    MONGODB_USER: root
    MONGODB_PASSWORD: suasenha
    MONGODB_HOST: mongo_catalog
    MONGODB_PORT: 27017
    MONGODB_DBNAME: catalog
    INSERT_PRODUCTS: 1
    REDIS_PORT: 6379
    REDIS_HOST: redis_catalog
    REDIS_PASSWORD: suasenha
  ports:
   - "3000:3000"
  depends_on:
   - "redis_catalog"
   - "mongo_catalog"
  links:
   - redis_catalog:redis_catalog
   - mongo_catalog:mongo_catalog
  networks:
   - shared
 mongo_catalog:
  image: mongo:3.4.2
  environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=suasenha
  ports:
   - "27017:27017"
  command: mongod
  networks:
   - shared
  logging:
   driver: none
 redis_catalog:
  image: "redis:alpine"
  command: redis-server --requirepass suasenha
  ports:
   - "6379:6379"
  networks:
   - shared
  logging:
   driver: none
 redis_recommendation:
  image: "redis:alpine"
  command: redis-server --requirepass suasenha --port 6380
  ports:
   - "6380:6380"
  networks:
   - shared
  logging:
   driver: none
networks:
 shared: